#!/bin/bash

current_branch=$(git symbolic-ref --short HEAD)
branches=()
eval "$(git for-each-ref --shell --format='branches+=(%(refname:short))' refs/heads/)"

if [ -z "$(git status --porcelain)" ]; then
    for branch in "${branches[@]}"; do
        git checkout $branch
        git pull
    done
    git checkout $current_branch
else
    echo "Uncommitted or unstaged changes."
fi

