#!/bin/sh

branch=$1

test -z $branch && echo "branch required." 1>&2 && exit 1

if [ -z "$(git status --porcelain | awk '// {if ($1 != "??") {print $0}}')" ]; then
    git checkout -b $branch
    git push --set-upstream origin $branch
else
    echo "Error: uncommitted changes."
fi

