#!/bin/sh

current_branch=$(git symbolic-ref --short HEAD)

if [ -z "$(git status --porcelain) | awk '// {if ($1 != "??") {print $0}}')" ]; then
    git pull
    git checkout master
    git pull
    git checkout $current_branch
    git merge master
else
    echo "Uncommitted changes."
fi

