#!/bin/sh

__update_git () {
    if [ -z "$(git status --porcelain | awk '// {if ($1 != "??") {print $0}}')" ]; then
        git pull
        git checkout $1
        git pull
        git checkout $2
        git merge $1
    else
        echo "Uncommitted changes."
    fi
}

source_branch=${@:-master}
current_branch=$(git symbolic-ref --short HEAD)

__update_git $source_branch $current_branch
