#!/usr/bin/python

import os
import subprocess as sp

from tools import files_to_link, links_location

link_command = ['ln', '-s']

if __name__ == '__main__':
    repo_dir = os.path.dirname(os.path.realpath(__file__))
    for f in files_to_link:
        print "Installing git utility %s" % f
        sp.call(link_command + [os.path.join(repo_dir, f),
                                os.path.join(links_location, f)])
