#!/usr/bin/python

import os
import subprocess as sp

from tools import files_to_link, links_location

rem_command = ['rm']

if __name__ == '__main__':
    for f in files_to_link:
        print "Removing git utility %s" % f
        sp.call(rem_command + [os.path.join(links_location, f)])

