#!/bin/sh

branch=$1

test -z $branch && echo "branch required." 1>&2 && exit 1

if [ -z "$(git status --porcelain)" ]; then
    git checkout -b $branch
    git push --set-upstream origin $branch
else
    echo "Uncommitted or unstaged changes."
fi

