#!/bin/sh

current_branch=$(git symbolic-ref --short HEAD)

if [ -z "$(git status --porcelain)" ]; then
    git pull
    git checkout master
    git pull
    git checkout $current_branch
    git merge master
else
    echo "Uncommitted or unstaged changes."
fi

