#!/bin/sh

branch=$1

test -z $branch && echo "Branch required." 1>&2 && exit 1

if [ -z "$(git status --porcelain)" ]; then
    echo "Checkout & sync master..."
    git checkout master
    git pull
    echo Creating new branch $branch with upstream...
    git checkout -b $branch
    git push --set-upstream origin $branch
else
    echo "Uncommitted or unstaged changes."
fi

